### ISSUE TITLE
Support .zip assets in github releases

### ISSUE THREAD

**Issue by li-yunjie** [kitasuke/MVVMLint#1]
Hi @kitasuke san!

Our team is using MVVMLint, and have found several cases of unused code and missing implementation, it's been very helpful and we want to keep using it.
To allow us to integrate this tool in our circleCI workflow, we need to be able to download it from github's `release` API. It's easier than adopting homebrew, now we use this method with sportify's [XCLogParser](https://github.com/spotify/XCLogParser).

Can you please take a look at XCLogParser's [release](https://github.com/spotify/XCLogParser/releases) page, and do the following for MVVMLint:
- compress the project into zip file
- upload to github release assets

Now I'm able to download mvvm using `curl`, but the project cannot be opened because it doesn't belong to any recognizable format. Once it changes to `zip`, I will be able to unzip it, make it executable and run it in circleCI.

Thank you very much for making this tool, and I hope everything is well!
Looking forward to hear back from you.

**Comment by kitasuke** [comment]
Thanks for your feedback!
It's done here. Can you make sure if this works?
https://github.com/kitasuke/MVVMLint/releases/tag/0.2.0

**Comment by li-yunjie** [comment]
@kitasuke Thank you very much!
Sorry about late reply, I verified we can download mvvmlint 0.2.0 from github release and use it on circleCI 🎉 🙇‍♀

**Comment by kitasuke** [comment]
Cool!
